# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='제목은 필수입니다.', max_length=200, verbose_name='제목'),
        ),
    ]
