# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160127_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '블로그'},
        ),
    ]
