# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160127_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': '포스트'},
        ),
    ]
